#pragma once

#include <glad/glad.h>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>

#include <cstddef>
#include <vector>

#include <glm/vec2.hpp>

struct Vertex
{
    glm::vec3 position;
    glm::vec3 normal;
    glm::vec2 texCoord;
};

class Mesh
{
public:
    Mesh() = default;
    Mesh(const std::vector<Vertex>& vertices, const std::vector<unsigned int>& indices);
    ~Mesh();

    Mesh(const Mesh&) = delete;
    Mesh& operator=(const Mesh&) = delete;

    Mesh(Mesh&& other) noexcept;
    Mesh& operator=(Mesh&& other) noexcept;

    void draw() const;

    static Mesh makeCube();
    static Mesh makeBeveledCube(float bevel = 0.08f);
    static Mesh makeCarCabin();
    static Mesh makeCylinder(unsigned int segments = 32);

    // Surface of revolution generated by sweeping a Bezier curve around the
    // Y axis - the Lab 5 construction. Control points are (radius, height)
    // pairs in metres, so the profile is authored in world units and the mesh
    // needs no extra scaling. `stacks` samples the curve, `slices` samples the
    // sweep around the axis.
    static Mesh makeBezierRevolution(
        const std::vector<glm::vec2>& controlPoints,
        unsigned int stacks = 20,
        unsigned int slices = 24);

private:
    GLuint vao_ = 0;
    GLuint vbo_ = 0;
    GLuint ebo_ = 0;
    GLsizei indexCount_ = 0;

    void release();
};
