#pragma once

#include <glad/glad.h>
#include <glm/mat4x4.hpp>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>

#include <cstddef>
#include <vector>

struct Vertex
{
    glm::vec3 position;
    glm::vec3 normal;
    glm::vec2 texCoord;
    // Multiplies the material colour, so one baked mesh can hold many
    // differently painted things. Alpha carries a per-object number: the
    // seed of a building's lit windows, or how far a leaf sways in the wind.
    glm::vec4 color {1.0f};
};

// One copy of a mesh in an instanced draw: where it goes, and its colour
// (multiplying the vertex colour; the alpha is how brightly it glows).
struct InstanceData
{
    glm::mat4 model {1.0f};
    glm::vec4 color {1.0f, 1.0f, 1.0f, 0.0f};
};

// A buffer of instances, refilled every frame. It grows as needed and never
// shrinks, so once warmed up a frame does not reallocate it.
class InstanceBuffer
{
public:
    InstanceBuffer() = default;
    ~InstanceBuffer();
    InstanceBuffer(const InstanceBuffer&) = delete;
    InstanceBuffer& operator=(const InstanceBuffer&) = delete;

    void upload(const std::vector<InstanceData>& instances);
    GLuint id() const { return vbo_; }

private:
    GLuint vbo_ = 0;
    std::size_t capacity_ = 0;
};

// Geometry on the CPU side, before it is uploaded. Kept separately so the
// same shape can also be baked many times into one combined mesh.
struct MeshData
{
    std::vector<Vertex> vertices;
    std::vector<unsigned int> indices;
};

class Mesh
{
public:
    Mesh() = default;
    Mesh(const std::vector<Vertex>& vertices, const std::vector<unsigned int>& indices);
    explicit Mesh(const MeshData& data) : Mesh(data.vertices, data.indices) {}
    ~Mesh();

    Mesh(const Mesh&) = delete;
    Mesh& operator=(const Mesh&) = delete;

    Mesh(Mesh&& other) noexcept;
    Mesh& operator=(Mesh&& other) noexcept;

    void draw() const;
    // `count` copies in one draw call, each placed and painted by the
    // buffer's instances (vertex attributes 4 to 8, one step per copy).
    void drawInstanced(const InstanceBuffer& instances, std::size_t count) const;
    bool empty() const { return indexCount_ == 0; }

    // Draw calls issued since the last reset, for the HUD.
    static int drawCalls() { return drawCalls_; }
    static void resetDrawCalls() { drawCalls_ = 0; }

    // A point on a Bezier curve of any degree, in the Bernstein form of the
    // Lab 5 program. Used for the surfaces of revolution below and for the
    // side profiles of the vehicle bodies (VehicleRenderer.cpp).
    static glm::vec2 bezier(float t, const std::vector<glm::vec2>& controlPoints);

    static MeshData beveledCubeData(float bevel = 0.08f);
    static MeshData cylinderData(unsigned int segments = 32);
    static MeshData bezierRevolutionData(
        const std::vector<glm::vec2>& controlPoints, unsigned int stacks, unsigned int slices);

    static Mesh makeCube();
    static Mesh makeBeveledCube(float bevel = 0.08f);
    static Mesh makeCarCabin();
    static Mesh makeCylinder(unsigned int segments = 32);

    // Surface of revolution generated by sweeping a Bezier curve around the
    // Y axis - the Lab 5 construction. Control points are (radius, height)
    // pairs in metres, so the profile is authored in world units and the mesh
    // needs no extra scaling. `stacks` samples the curve, `slices` samples the
    // sweep around the axis.
    static Mesh makeBezierRevolution(
        const std::vector<glm::vec2>& controlPoints,
        unsigned int stacks = 20,
        unsigned int slices = 24);

private:
    GLuint vao_ = 0;
    GLuint vbo_ = 0;
    GLuint ebo_ = 0;
    GLsizei indexCount_ = 0;
    static inline int drawCalls_ = 0;

    void release();
};
